name: Full-scale-scrapper

on:
  workflow_dispatch:

jobs:
  fetch_trends:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index-range:
          - { start: 1, end: 250 }
          - { start: 251, end: 500 }
          - { start: 501, end: 750 }
          - { start: 751, end: 1000 }
          - { start: 1001, end: 1250 }
          # Add more ranges as needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          START_INDEX: ${{ matrix.index-range.start }}
          END_INDEX: ${{ matrix.index-range.end }}
          CSV_FILE_PATH: "/Users/yavaren/Documents/Documents/Spirex/spirex-data/product-list/apparel_and_clothes-eng.csv"
        run: |
          cd $GITHUB_WORKSPACE
          python fetch_trends.py

      - name: Upload data artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-trends-data-${{ matrix.index-range.start }}-to-${{ matrix.index-range.end }}
          path: data/combined_trends_data_${{ matrix.index-range.start }}_to_${{ matrix.index-range.end }}.csv

  merge_results:
    runs-on: ubuntu-latest
    needs: fetch_trends
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download data artifacts
        uses: actions/download-artifact@v2
        with:
          name: combined-trends-data-*
          path: data/

      - name: Merge data files
        run: |
          cd $GITHUB_WORKSPACE
          python merge_files.py

      - name: Upload final merged data artifact
        uses: actions/upload-artifact@v3
        with:
          name: final-merged-trends-data
          path: data/final_combined_trends_data.csv
