name: Full-scale-scrapper

on:
  workflow_dispatch:

jobs:
  fetch_trends:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Display Python version
        run: python --version

      - name: Create virtual environment
        run: |
          echo "Creating virtual environment"
          python -m venv venv
        shell: bash

      - name: Debug virtual environment
        run: |
          echo "Listing venv/bin directory contents"
          ls -alh venv/bin
        shell: bash

      - name: Install dependencies
        run: |
          echo "Activating virtual environment and installing dependencies"
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Run script
        env:
          START_INDEX: 1
          END_INDEX: 250
          CSV_FILE_PATH: product-list/apparel_and_clothes.csv
        run: |
          echo "Running fetch_trends.py"
          source venv/bin/activate
          python fetch_trends.py
        shell: bash

      - name: Upload data artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-trends-data
          path: data/combined_trends_data_1_to_250.csv
